--liquibase formatted sql

--Сгенирован с помошью pg_dump, с начало ddl-auto -> update, потом после всего validate

--changeset zhavokhir:5.1
CREATE TABLE public.person_aud (
                                   id bigint NOT NULL,
                                   rev integer NOT NULL,
                                   revtype smallint,
                                   birth_date date,
                                   email character varying(255),
                                   firstname character varying(255),
                                   image character varying(255),
                                   lastname character varying(255),
                                   password character varying(255),
                                   phone_number character varying(255),
                                   role character varying(255),
                                   CONSTRAINT person_aud_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);

--changeset zhavokhir:5.2
CREATE TABLE public.revision (
                                 id integer NOT NULL,
                                 "timestamp" timestamp(6) with time zone
);

--changeset zhavokhir:5.3
ALTER TABLE public.revision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

--changeset zhavokhir:5.4
ALTER TABLE ONLY public.person_aud
    ADD CONSTRAINT person_aud_pkey PRIMARY KEY (rev, id);

--changeset zhavokhir:5.5
ALTER TABLE ONLY public.revision
    ADD CONSTRAINT revision_pkey PRIMARY KEY (id);

--changeset zhavokhir:5.6
ALTER TABLE ONLY public.person_aud
    ADD CONSTRAINT fkc5na6emj2l0ir751jxn1bl3ix FOREIGN KEY (rev) REFERENCES public.revision(id);